name=SmartProcess
version=1.0.1
author=Jayasankar JP
maintainer=Jayasankar JP <scicopath01@gmail.com>
sentence=Smart timer trigger library for Arduino
paragraph=Provides a clean and simple timer-based trigger system compatible with Arduino IDE and CLI.
category=Timing
url=https://github.com/jayasankar-jp/SmartProcess
architectures=*